package models

type Physics struct {
	PacketID           int32
	Gas                float32
	Brake              float32
	Fuel               float32
	Gear               int32
	RPM                int32
	SteerAngle         float32
	SpeedKmh           float32
	Velocity           Vector
	AccG               Vector
	WheelSlip          Wheels
	WheelLoad          Wheels
	WheelPressure      Wheels
	WheelAngularSpeed  Wheels
	TyreWear           Wheels
	TyreDirtyLevel     Wheels
	TyreCoreTemp       Wheels
	CamberRAD          Wheels
	SuspensionTravel   Wheels
	Drs                float32
	TC                 float32
	Heading            float32
	Pitch              float32
	Roll               float32
	CGHeight           float32
	CarDamage          CarDamage
	NumberOfTyresOut   int32
	PitLimiterOn       int32
	ABS                float32
	KersCharge         float32
	KersInput          float32
	AutoshifterOn      int32
	RideHeight         [2]float32
	TurboBoost         float32
	Ballast            float32
	AirDensity         float32
	AirTemp            float32
	RoadTemp           float32
	LocalAngularVel    Vector
	FinalFF            float32
	PerformanceMeter   float32
	EngineBrake        int32
	ERSRecoveryLevel   int32
	ERSPowerLevel      int32
	ERSHeatCharging    int32
	ERSIsCharging      int32
	KersCurrentKJ      float32
	DrsAvailable       int32
	DrsEnabled         int32
	BrakeTemp          Wheels
	Clutch             float32
	TyreTempI          Wheels
	TyreTempM          Wheels
	TyreTempO          Wheels
	IsAIControlled     int32
	TyreContactPoint   TireContactPoints
	TyreContactNormal  TireContactPoints
	TyreContactHeading TireContactPoints
	BrakeBias          float32
	LocalVelocity      Vector
	P2PActivation      int32
	P2PStatus          int32
	CurrentMaxRPM      float32
	Mz                 Wheels
	Fx                 Wheels
	Fy                 Wheels
	SlipRatio          Wheels
	SlipAngle          Wheels
	TCInAction         int32
	ABSInAction        int32
	SuspensionDamage   Wheels
	TyreTemp           Wheels
	WaterTemp          float32
	BrakePressure      Wheels
	FrontBrakeCompound int32
	RearBrakeCompound  int32
	PadLife            Wheels
	DiscLife           Wheels
	IgnitionOn         int32
	StarterEngineOn    int32
	IsEngineRunning    int32
	KerbVibration      float32
	SlipVibrations     float32
	GVibrations        float32
	ABSVibrations      float32
}
